apiVersion: apps/v1
kind: Deployment
metadata:
  name: theforce-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: theforce
  template:
    metadata:
      labels:
        app: theforce
    spec:
      containers:
      - name: theforce
        image: theforce-service
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"